### ISSUE TITLE
Question about dependency-based SRL English Data with PropBank3 frames

### ISSUE THREAD

**Issue by aminianmary** [System-T/UniversalPropositions#3]
Hi,
Thanks for releasing the data!
Is there any **dependency-based** SRL English data with PropBank3 frames and roles? 
--Maryam

**Comment by cgraywang** [comment]
Hi,

Thanks for your interests! For English SRL, we are using PropBank3 frames and roles which includes dependency information to train the SRL model. Then our Universal PropBank is generated based on our ACL'15 paper using parallel corpus which also contains the dependency information projected from the SRL model labeled English data. To generate the SRL labeled corpus for different languages, we are using different corpus. So for now, I suggest you to use PropBank3 if you are focusing on English. For other languages, please feel free to download the released Universal PropBank and try it out! 

Best,
Ray

**Comment by aminianmary** [comment]
Hi Ray, Thanks for your reply.

**Comment by yunyaoli** [comment]
Closed as the issue has been resolved.
