### ISSUE TITLE
question about evaluation dependency based srl

### ISSUE THREAD

**Issue by edchengg** [System-T/UniversalPropositions#9]
Hi,
What should be a proper evaluation metric for dependency-based srl?
For example, F1-measure but what kind of criteria should I consider (role label, position)?
Thanks

**Comment by yunyaoli** [comment]
@edchengg You can refer to the CoNLL-2009 Shared Task Scorer for such details: http://ufal.mff.cuni.cz/conll2009-st/scorer.html
